<?php

$lang['Admin'] = array(
    'Panel' => 'Panel',
    'Panel01' => 'Yalnızca destek hesabı için yönetici paneli.',
    'Panel02' => 'Panele git',

    'Message' => 'Mesaj',
    'Gold' => 'Altın',
    'Player' => 'Oyuncular',
    'Hour' => 'Saat',
    'Day' => 'Gün',
    'Forever' => 'Sonsuza dek',
    'Confirm' => 'Onayla',

    'sidebar01' => 'Ana sayfa',
    'sidebar02' => 'Oyuncular',
    'sidebar03' => 'Oyuncu listesi',
    'sidebar04' => 'Aktif oyuncular',
    'sidebar05' => 'Aktif olmayan oyuncular',
    'sidebar06' => 'Çoklu hesap tespiti',
    'sidebar07' => 'Toplu mesajlar',
    'sidebar08' => 'Sistem mesajı',
    'sidebar09' => 'Oyuncu postaları',
    'sidebar10' => 'Oyuncudan altın al',
    'sidebar11' => 'Oyuncuyu engelle/engeli kaldır',
    'sidebar12' => 'Arama',
    'sidebar13' => 'Köy, oyuncu, ittifak',
    'sidebar14' => 'Mesajları ve raporları kontrol et',
    'sidebar15' => 'Altın',
    'sidebar16' => 'Tüm oyunculara altın ekle',
    'sidebar17' => 'Bir oyuncuya altın ver',
    'sidebar18' => 'Sistem',
    'sidebar19' => 'Kayıtları kapat',
    'sidebar20' => 'Vahşileri boşalt',
    'sidebar21' => 'Natar çiftlikleri ekle',
    'sidebar22' => 'Mesaj listeleri',
    'sidebar23' => 'Sunucu ayarları',
    'sidebar24' => 'Genel ayarlar',
    'sidebar25' => 'Sunucu saatleri',
    'sidebar26' => 'Plus ayarları',
    'sidebar27' => 'Oyuna geri dön',
    'sidebar28' => 'Çıkış yap',
    'sidebar29' => 'Tüm telif hakları',

    'home01' => 'Yönetici paneli',
    'home02' => 'Hoş geldiniz',
    'home03' => 'Giriş yaptınız:',
    'home04' => 'Çoklu hesap avcısı',
    'home05' => 'Oyuncu sayısı',
    'home06' => 'Oyuncular',
    'home07' => 'Irkını ve köy yerini seçmiş aktif oyuncuların toplamı',
    'home08' => 'Sipariş sayısı',
    'home09' => 'Siparişler',
    'home10' => 'Sunucuda otomatik olarak PayPal ile ödenmiş tüm altın siparişleri sayısı',
    'home11' => 'Kazanılan para',
    'home12' => 'Otomatik PayPal ödemeleriyle kazanılan toplam para',
    'home13' => 'Destek Mesajları',
    'home14' => 'Giriş ve kayıt sayfalarındaki destek formundan gelen mesaj sayısı (oyun içi mesajlar hariç)',
    'home15' => 'Toplam altın',
    'home16' => 'Oyunda oyuncuların sahip olduğu toplam altın (canlı veri, güncellemek için sayfayı yenileyin)',
    'home17' => 'Online oyuncular',
    'home18' => 'Şu anda oyunda çevrimiçi olan oyuncular (canlı veri, güncellemek için sayfayı yenileyin)',

    'players01' => 'Oyuncu listesi',
    'players02' => 'Kullanıcı adı [erişim]',
    'players03' => 'Kayıt tarihi',
    'players04' => 'Irk',
    'players05' => 'Nüfus',
    'players06' => 'Köyler',
    'players07' => 'Altın',

    'online01' => 'Çevrimiçi oyuncular',
    'online02' => 'Çevrimiçi oyuncu bulunamadı',

    'notregistered01' => 'Aktif olmayan oyuncular (henüz hesaplarını aktifleştirmemişler)',
    'notregistered02' => 'ID',
    'notregistered03' => 'Oyuncu',
    'notregistered04' => 'E-posta',
    'notregistered05' => 'Irk',
    'notregistered06' => 'Aktivasyon kodu',
    'notregistered07' => 'Akt 2',
    'notregistered08' => 'Kayıt tarihi',

    'multi01' => 'Çoklu hesap dedektörü',
    'multi02' => 'Hesaplar',
    'multi03' => 'IP',

    'global01' => 'Global mesaj',
    'global02' => 'Gönder',

    'ban01' => 'Oyuncuyu yasakla',
    'ban02' => 'Cezalandır',
    'ban03' => 'Hile',
    'ban04' => 'Hack',
    'ban05' => 'Hata kullanımı',
    'ban06' => 'Yasaklı isim',
    'ban07' => 'Çoklu hesap',
    'ban08' => 'Küfür',
    'ban09' => 'Oyuncu',
    'ban10' => 'Sebep',
    'ban11' => 'Süre',
    'ban12' => 'Yasaklı oyuncular',
    'ban13' => 'Süre (Başlangıç/Bitiş)',
    'ban14' => 'Yasaklı oyuncu bulunamadı',

    'search01' => 'Arama',
    'search02' => 'Oyuncu ara',
    'search03' => 'İttifak ara',
    'search04' => 'Köy ara',
    'search05' => 'E-posta ara',
    'search06' => 'IP adresi ara',
    'search07' => 'Silinmiş oyuncu ara',
    'search08' => 'Oyuncu silinmiş.',
    'search09' => 'Oyuncu',
    'search10' => 'Köyler',
    'search11' => 'Nüfus',
    'search12' => 'İttifaklar',
    'search13' => 'İsim',
    'search14' => 'Etiket',
    'search15' => 'Sahibi',
    'search16' => 'Köyler',
    'search17' => 'Köy ismi',
    'search18' => 'Sahibi',
    'search19' => 'Nüfus',
);

$lang['AError'] = array(
    'err01' => 'Kullanıcı adı veya şifre yanlış.',
);
